version: '3.8'

services:
  postgres:
    container_name: polls-pg
    image: postgres
    ports:
      - 5434:5434
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: polls
      PGPORT: 5434
    volumes:
      - polls_pg_data:/bitnami/postgresql

  redis:
    container_name: polls-cache
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'polls_redis_data:/bitnami/redis/data'

volumes:
  polls_pg_data:
  polls_redis_data: