# @name post-polls
POST http://localhost:3333/polls
Content-Type: application/json

{
  "title": "Qual é o melhor framework Node.js?",
  "options": ["Express", "Fastify", "Nest.js"]
}

###

# @name get-poll
GET http://localhost:3333/polls/942bf90e-5a4a-41e0-bf2c-c4ae1a184560

### 

# @name vote-on-poll
POST http://localhost:3333/polls/942bf90e-5a4a-41e0-bf2c-c4ae1a184560/votes
Content-Type: application/json

{
  "pollOptionId": "f1adf9d0-3e09-4761-88b9-b49b9bd14a2e"
}